# -*- coding: utf-8 -*-
"""Fibonacci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lKJpo3ulRswNLAr0qQhos7gYNdaUHRWS
"""

# Последовательность Фибоначчи : 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233...

n = int(input())
f1, f2 = 1, 1 # если последовательность начинается с 1
for i in range(n):
    print(f1, end=' ')
    f1, f2 = f2, f1 + f2