# -*- coding: utf-8 -*-
"""числовая угадайка

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HuTWIhj54krA5if5IZ0oxQfhmANv6tW8
"""

import random
num = random.randint(1, 100)
print('Добро пожаловать в числовую угадайку')
def is_valid(n):
    if n.isdigit() and 1 <= int(n) <= 100:
        return True
    else:
        return False
while True:
    n = input('Введите Ваше число от 1 до 100: ')
    if is_valid(n) == False:
        print('А может быть все-таки введем целое число от 1 до 100?')
    if is_valid(n) == True:
        n = int(n)
        if n < num:
            print('Ваше число меньше загаданного, попробуйте еще разок')
        if n > num:
            print('Ваше число больше загаданного, попробуйте еще разок')
        if n == num:
            print('Вы угадали, поздравляем!')
            break
print('Спасибо, что играли в числовую угадайку. Еще увидимся...')