# -*- coding: utf-8 -*-
"""шифр Цезаря

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CtvJSzh8oySXiZVEJYzB1opLv64CztZp
"""

# шифр Цезаря
def caesar_shifr(text, alphabet, shift, direct='ENCODE'):
    alphabet_lenght = len(alphabet)
    result = ''
    for i in range(len(text)):
        if text[i].lower() in alphabet:
            place = alphabet.index(text[i].lower())
            if direct == 'ENCODE':
                index = (place + shift) % alphabet_lenght
            else:
                index = (place - shift) % alphabet_lenght
            result += (alphabet[index].upper() if text[i].isupper() else alphabet[index])
        else:
            result += text[i]
    return result

print("*" * 5, "Шифр Цезаря", "*" * 5)
print()
lang = input('Выберите язык (RU или EN): ')
direct = input('Шифруем или дешифруем (ENCODE или DECODE): ')
shift = int(input('Укажите сдвиг вправо (числовое значение): '))
text = input('Введите свой текст: ')

if lang.upper() == 'RU':
    alphabet = 'абвгдежзийклмнопрстуфхцчшщъыьэюя'
else:
    alphabet = 'abcdefghijklmnopqrstuvwxyz'

print()
print(('Текст зашифрован!' if direct == 'ENCODE' else 'Текст расшифрован!'))
print('-' * 20)
password = caesar_shifr(text, alphabet, shift, direct)
print(password)
print('-' * 20)